begin;

-- Epica 2 slice 3 fix round (RULING 48): bind every transaction's account to
-- the transaction's own workspace.
--
-- Defect: transactions.account_id referenced public.accounts(id) ALONE.
-- Nothing tied the referenced account's workspace to the transaction's
-- workspace, and PostgreSQL referential-integrity checks bypass row security
-- by design, so a member of workspace A could insert a contract-legal
-- transaction in wsA pointing at an account of workspace B (the insert policy
-- only checks the actor's role on transactions.workspace_id). The resulting
-- poison row then bricked DELETE /v1/workspaces/wsB permanently: the cascade
-- reached wsB's account, restrict found the surviving wsA transaction, raised
-- 23503, and the whole delete rolled back -- unremovable through the API
-- because transactions has no delete grant and voiding keeps the physical row
-- that RI still sees regardless of status or RLS visibility.
--
-- The fix makes the cross-workspace reference UNREPRESENTABLE rather than
-- merely refused. Every transaction now necessarily shares its account's
-- workspace, so a workspace cascade takes its transactions with it and the
-- denial of service is dissolved structurally.

-- A composite foreign key needs a matching unique constraint on the
-- referenced side; id alone no longer carries the reference.
alter table public.accounts
  add constraint accounts_workspace_id_id_key unique (workspace_id, id);

-- Resolve the pre-existing single-column account_id FK BY SHAPE from the
-- catalog, never by hardcoded name: autogenerated constraint names truncate
-- at 63 characters. `select ... into strict` raises unless EXACTLY ONE
-- constraint matches -- a plain `select into` caps ROW_COUNT at 1 and so
-- cannot detect the more-than-one case.
do $$
declare
  v_account_attnum smallint;
  v_old_fk_name text;
begin
  select a.attnum into strict v_account_attnum
    from pg_attribute a
   where a.attrelid = 'public.transactions'::regclass
     and a.attname = 'account_id'
     and not a.attisdropped;

  select c.conname into strict v_old_fk_name
    from pg_constraint c
   where c.conrelid = 'public.transactions'::regclass
     and c.contype = 'f'
     and c.confrelid = 'public.accounts'::regclass
     and cardinality(c.conkey) = 1
     and c.conkey = array[v_account_attnum]::smallint[];

  execute format('alter table public.transactions drop constraint %I',
                 v_old_fk_name);
end $$;

alter table public.transactions
  add constraint transactions_account_workspace_fkey
  foreign key (workspace_id, account_id)
  references public.accounts (workspace_id, id)
  -- Accounts are closed, never deleted (PRD:519): restrict preserves
  -- financial history if one ever is removed out-of-band, and set null would
  -- violate the column's not-null invariant. The defect was the missing
  -- workspace binding, not this action.
  on delete restrict;

commit;
